module SkelGrammar where

-- Haskell module generated by the BNF converter
import AbsGrammar
import qualified Data.Map as Map
import qualified TypeCheck(checkType)
import qualified Stmt(transProgram)

